USE 5ai_19_20_s01118;

CREATE TABLE IF NOT EXISTS 191203_attore (
	codAttore INT(11) NOT NULL AUTO_INCREMENT,
	nome VARCHAR(30) DEFAULT NULL,
	cognome VARCHAR(30) NOT NULL,
	annoNascita YEAR DEFAULT NULL,
	nazionalita VARCHAR(30) DEFAULT NULL,
	PRIMARY KEY(codAttore)
);

CREATE TABLE IF NOT EXISTS 191203_film (
	codFilm INT(11) NOT NULL AUTO_INCREMENT,
	titolo VARCHAR(50) NOT NULL UNIQUE,
	AnnoProduzione YEAR NOT NULL,
	nazionalita VARCHAR(30),
	regista VARCHAR(30) NOT NULL,
	genere VARCHAR(50),
	PRIMARY KEY(codFilm)
);

CREATE TABLE IF NOT EXISTS 191203_sala (
	codSala INT(11) NOT NULL AUTO_INCREMENT,
	posti INT(10) NOT NULL,
	nome VARCHAR(30) DEFAULT SET NULL,
	citta VARCHAR(50) NOT NULL,
	PRIMARY KEY(codSala)
);

CREATE TABLE IF NOT EXISTS 191203_recita (
	codAttore INT(11) NOT NULL,
	codFilm INT(11) NOT NULL,
	PRIMARY KEY(codAttore, codFilm),
	FOREIGN KEY(codAttore) REFERENCES 191203_attore(codAttore),
	FOREIGN KEY(codFilm) REFERENCES 191203_film(codFilm)
);

CREATE TABLE IF NOT EXISTS 191203_proiezione (
	codProiezione INT(11) NOT NULL AUTO_INCREMENT,
	codFilm INT(11) NOT NULL,
	codSala INT(11) NOT NULL,
	incasso FLOAT(10) DEFAULT SET 0,
	dataProiezione DATETIME,
	PRIMARY KEY(codProiezione),
	FOREIGN KEY(codFilm) REFERENCES 191203_film(codFilm),
	FOREIGN KEY(codSala) REFERENCES 191203_sala(codSala)
);
