-- #
-- # TABLE STRUCTURE FOR: Sequestro
-- #
--
-- DROP TABLE IF EXISTS `Sequestro`;
--
-- CREATE TABLE `Sequestro` (
--   `ID` int(11) NOT NULL AUTO_INCREMENT,
--   `Descrizione` text COLLATE utf8_bin NOT NULL,
--   `Data_ritiro` datetime DEFAULT NULL,
--   PRIMARY KEY (`ID`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DELETE FROM `Sequestro`;

INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (1, 'Velit ea perspiciatis ut minima id exercitationem aut. Nemo cum saepe dolor sed voluptatum consequatur et.', '1988-05-27 20:06:06');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (2, 'Molestiae laudantium et laborum. Rerum qui qui asperiores ut repellat aut.', '1971-01-03 14:35:52');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (3, 'Qui sed consequatur commodi debitis necessitatibus debitis aut. Aliquid excepturi quidem omnis nihil eligendi. Velit doloribus minus reprehenderit. Qui rem error nesciunt ut eveniet ab.', '1984-03-26 05:39:43');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (4, 'Qui et saepe et et voluptas quis. Sit perferendis voluptatem asperiores autem velit qui repellendus omnis.', '2010-03-03 13:34:58');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (5, 'Perferendis quibusdam deserunt qui consequatur sit ad. Minus odio consequatur aperiam architecto cumque tenetur ipsa. Unde dolore dolores voluptas temporibus explicabo alias.', '1976-10-28 17:23:51');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (6, 'Possimus dolor animi qui enim. Nostrum et et esse possimus porro nobis debitis. Modi dolorem odio consequatur et. Dolore dolorem nihil repellendus eligendi consequatur.', '2011-10-23 05:00:51');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (7, 'Labore quibusdam laudantium suscipit. Molestiae dolores et et praesentium voluptatum quo. Placeat repudiandae repudiandae in neque aliquam. Architecto adipisci animi non nihil.', '1994-04-17 19:18:24');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (8, 'Hic et dolor assumenda consequatur. In eum mollitia quia vero quo. Deleniti et quis soluta. Magnam occaecati ipsa deserunt nam. Sapiente qui possimus nemo quo officiis minima.', '1976-10-20 13:24:25');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (9, 'Iste enim non sunt atque nam sit. Dolor deserunt vel cum repellendus est ad nesciunt. Blanditiis accusantium ut excepturi quasi aut fuga voluptas.', '2011-12-11 16:01:45');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (10, 'Ut labore a dolores consequatur amet nobis. Quia veritatis neque corrupti saepe consequuntur. Accusantium ex omnis qui est et.', '2011-01-10 22:49:22');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (11, 'Adipisci non tenetur est odio quos et. Tempora dolorum magni tenetur explicabo ratione nostrum quo.\nQuia sequi fugiat ut. Exercitationem mollitia tempore nulla pariatur ut.', '1999-06-08 23:44:38');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (12, 'Minus similique excepturi corporis sit doloribus. Nostrum id nihil laborum fuga. Dolores quasi totam officia iste et ea deleniti. Culpa consequatur rem mollitia debitis harum atque.', '1970-08-06 12:41:21');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (13, 'Reiciendis nihil iste asperiores repudiandae aut tenetur. Iusto officiis debitis mollitia dicta eos tenetur.', '1980-02-13 00:22:19');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (14, 'Quo illo sed temporibus maxime. Assumenda voluptates pariatur at fuga in hic. Molestiae vero quas facere natus.\nExplicabo eum laborum aspernatur libero in quae. Quae provident sed voluptatibus.', '1982-11-01 00:06:20');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (15, 'Vero veritatis recusandae quod reiciendis. Dicta dolorem explicabo dolor. Labore eos dolorem voluptas quod. Dicta voluptatem facere similique reprehenderit.', '2017-08-01 12:43:00');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (16, 'Id qui atque facere iste quia eveniet. Occaecati corrupti repellat sunt perferendis saepe corrupti. Natus sed molestiae ea corporis repellendus quidem unde.', '1982-12-29 11:43:55');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (17, 'Facilis dolor beatae temporibus facere quae doloribus est. Nihil et aut accusamus est voluptas. Nihil minima exercitationem omnis quam. Sit maxime vitae explicabo commodi.', '2001-11-26 14:06:54');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (18, 'Molestiae non ad suscipit error veniam ullam. Incidunt maiores cum ea magnam quibusdam consequuntur. Sint officia corrupti maxime repellat inventore repellat. Tempora qui quasi fugiat.', '1973-07-25 00:25:57');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (19, 'Culpa porro sunt dolores et beatae. Ea eum voluptates qui nulla eos. Sed fugit dolorem veritatis et doloribus qui magni. Quia et dolorem voluptas labore illum.', '1982-12-02 17:32:24');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (20, 'Est ut rem quasi accusantium dolores ex. Minima voluptatem et qui accusamus error. Eum qui est est atque autem. Quos ea deleniti ut quidem facilis eveniet.', '1989-11-09 22:06:40');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (21, 'Qui eligendi quos tenetur recusandae. Consequuntur nam pariatur quia aut ducimus. Doloribus eligendi iusto rerum omnis quia fugiat adipisci. Sit rerum adipisci nihil omnis autem.', '1973-03-15 22:20:43');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (22, 'Atque aut mollitia iste sit ipsum. Officia incidunt repellendus officiis quae exercitationem. Dolores quibusdam sint commodi ipsa sint harum ut.', '2006-05-22 04:47:17');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (23, 'Voluptatibus ut id quam iste officiis. Ab enim facere rem iusto deleniti sit. Ex consequatur sit in illo. Aut voluptas corrupti et ullam sit.', '2000-09-16 23:07:45');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (24, 'Est qui asperiores qui. Nulla eligendi qui soluta.', '1978-06-15 15:18:11');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (25, 'Esse dolores minima assumenda quo. Accusamus ea necessitatibus voluptate esse rerum expedita. Qui iusto dolore aut mollitia eos.', '2012-01-06 23:40:12');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (26, 'Eveniet modi dolor quasi assumenda. Ut velit velit nostrum eum autem. Nihil distinctio quae doloremque voluptatem.', '2006-07-17 10:24:40');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (27, 'Et occaecati quo est repellat inventore. Non repellat sapiente aliquam vero id quia aut. Error rerum accusantium ratione blanditiis magni. Aut voluptatem et nobis animi. At est est ut dolor.', '1995-07-30 18:54:09');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (28, 'Non non enim incidunt veniam sequi. Quasi sint quis minima explicabo officia sed animi.', '1978-06-22 14:24:31');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (29, 'Voluptas nihil rerum non quis assumenda perspiciatis. Necessitatibus earum error non omnis illum ut quae. Dolorum sapiente illo voluptas aut.', '2004-02-04 05:49:12');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (30, 'Iure et dolor dolor id. Eum et doloribus eligendi et ut repudiandae nihil natus. Aut voluptas ea nesciunt temporibus sapiente nisi.', '1990-11-19 08:15:04');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (31, 'Perferendis expedita occaecati autem ut deserunt. Laudantium sed repudiandae qui et ea. Harum fuga aut pariatur rerum necessitatibus ea.', '2019-07-01 03:43:06');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (32, 'Omnis doloremque itaque est molestiae nihil. Omnis sed nostrum asperiores. Aut excepturi tempore qui consectetur minima. Sint quam et sed aut hic eos alias.', '2004-01-04 13:54:20');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (33, 'Ut ipsum ut consequatur. Fugit similique quasi eveniet nam aut deserunt. Hic rerum velit et molestiae.', '1993-11-03 21:00:26');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (34, 'Maxime aut et non ea laboriosam tenetur. Aliquid ut quo non voluptates. Neque dolor voluptates ad vero tempora. Maxime hic non quia voluptatem officiis.', '1988-11-17 16:27:36');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (35, 'Deserunt voluptatem omnis maiores placeat aliquam. Perspiciatis magni deserunt aut. Pariatur blanditiis ducimus ut facere. Voluptatem et tempora repellat.', '1982-10-10 20:24:19');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (36, 'Earum ea nemo fugiat rem. Voluptatem quo alias minima aperiam est ut. Minus sint dolorum ut voluptas. Delectus exercitationem consequatur sapiente et expedita ratione.', '1996-04-24 20:05:51');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (37, 'Et laboriosam natus perspiciatis ipsa iusto. Sequi sequi aut quia ea ducimus officiis laboriosam. Quisquam quae perferendis nostrum dolores.', '1991-03-28 07:19:32');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (38, 'Praesentium temporibus ipsam esse dolore. Non molestias quam quibusdam repellendus necessitatibus ea. Et aut odio voluptatem quisquam.', '2006-06-30 14:42:30');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (39, 'Ut dicta culpa ullam velit eum. Esse enim laudantium ab soluta.', '2016-04-30 03:53:29');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (40, 'Eum iste tempora praesentium exercitationem eius ut. In est quaerat dolores et. Aliquid excepturi est amet suscipit. Omnis in at aliquid saepe rerum maxime nesciunt omnis.', '2010-04-16 11:22:39');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (41, 'Qui suscipit vero provident necessitatibus labore. Ullam nemo id corrupti non et. Est quis sequi occaecati praesentium a.', '2007-03-16 09:48:48');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (42, 'Eum doloremque aspernatur aut reiciendis. Voluptatibus fuga reiciendis quisquam et accusamus.', '1998-04-04 02:48:47');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (43, 'Vel earum quas totam molestiae vel ipsum et quis. Nihil nemo non aliquid sed. Perspiciatis sed facilis quam esse qui.', '1982-12-06 21:17:08');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (44, 'Maxime provident id itaque cumque voluptatibus modi qui. Illum numquam eaque vitae necessitatibus ut hic. Et blanditiis veritatis mollitia mollitia maiores unde commodi.', '1991-11-25 09:03:08');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (45, 'Cumque eius vel ut iusto. Pariatur ab nam assumenda explicabo.\nExcepturi ipsam vel odit eum magnam. Beatae consequatur ea officiis molestias doloribus quia.', '1977-01-10 11:26:20');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (46, 'Deleniti beatae quis non blanditiis nemo voluptatem recusandae. Cum quis et earum sapiente. Est ea maxime recusandae. Eligendi provident quisquam a eveniet.', '2009-07-09 13:52:42');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (47, 'Accusantium et magni quisquam quia ullam. Illo corrupti officiis est exercitationem accusantium impedit et. Autem quia est quas quas. Officia cum modi ut ratione eius maxime.', '1992-08-01 04:14:12');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (48, 'Dicta eos ab mollitia dolorem sed. Ab nam accusantium enim mollitia est. Consequuntur ut voluptas est sunt ea.', '2019-12-21 10:16:38');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (49, 'Autem autem voluptatem laboriosam at omnis. Neque aliquam eum quod excepturi. Sed rerum rerum perspiciatis nesciunt blanditiis quae blanditiis. Qui ut quia voluptas eaque.', '2014-06-13 12:24:52');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (50, 'Sed repellendus atque cum autem tenetur enim sint. Magni velit repellendus vel ullam. Unde minus quia qui iusto sed at sed. Sunt voluptatum autem non quis recusandae.', '2015-10-15 09:03:42');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (51, 'Qui ut est mollitia iure at aut in autem. Error voluptatum temporibus doloribus minima molestiae. Placeat laboriosam possimus natus incidunt.', '1985-02-14 13:03:39');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (52, 'Dolores quia minus et cumque facere quas iste. Expedita iusto soluta non nobis nostrum ut. Cumque accusantium autem sint vitae. Molestiae aliquam et quod quibusdam magni aperiam ipsam.', '1972-11-10 02:24:46');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (53, 'Dolore nobis rerum ratione magni. Magnam nemo sed quo perspiciatis maxime ducimus. Ipsum voluptate perspiciatis non culpa quos officiis eaque et.', '2019-10-16 03:49:29');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (54, 'Sed voluptate ut dolorem officia ipsam consequatur laudantium qui. Eveniet totam dignissimos mollitia. Aut et in nihil quis.', '1986-12-10 05:38:03');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (55, 'Facere sed ut quisquam dolorem in porro. Qui sed facilis dicta ut nobis ad officiis. Et sed est doloribus libero. Consequatur eius doloribus alias eum optio.', '1979-03-19 00:35:43');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (56, 'Voluptatem est est dolorum in ut. Quaerat quod soluta eum mollitia asperiores. Ipsa saepe sed voluptatem et.', '1970-09-23 08:34:27');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (57, 'Ut minima tenetur corporis aut ab sed fuga. Quibusdam itaque quod ipsum iusto est. Quia aut laborum aperiam possimus.', '1975-07-27 21:22:59');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (58, 'Esse eum esse nemo eum. Nisi ratione minus voluptatibus possimus rem dolorem. Rerum aut aut voluptatem.', '1973-01-27 17:21:08');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (59, 'Quis consequatur eius cum et sint in. Officiis nam doloremque at esse incidunt eveniet. Ut rerum voluptates illum.', '1994-12-29 10:34:01');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (60, 'In voluptatum eos dolore error voluptatem. Amet aperiam hic consequatur aut laboriosam eum sint. Reprehenderit fugiat et totam culpa quo.', '1977-10-16 17:36:03');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (61, 'Dolor rerum dolorum mollitia et. Aliquid temporibus et quod accusamus qui placeat dolorem. Iusto quo omnis voluptatem laborum asperiores voluptatum.', '2017-06-03 05:22:03');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (62, 'Sit est et ut magnam possimus quis necessitatibus quam. Sequi est error odio ipsa provident facilis nihil nihil. Labore aliquid omnis libero sapiente impedit illum culpa facilis.', '2008-09-14 03:25:57');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (63, 'Accusamus ut dolores veniam qui voluptas. Similique nulla ullam ut error ut quasi necessitatibus. Qui laborum repudiandae a.', '1988-04-20 18:09:08');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (64, 'Ab sequi nostrum quia corporis est et labore. A necessitatibus eos consequatur enim eos.', '1977-01-01 12:34:27');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (65, 'Porro officia vel est accusantium. Nesciunt consequuntur voluptatem ut nulla corrupti dicta vel harum. Sint fuga quos aspernatur dolorem. Ea repellendus aut similique porro provident.', '2016-05-19 06:19:59');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (66, 'Vitae temporibus minus ut ut consequatur totam. Eius est quaerat cumque dolores eos qui in. Qui dolores accusantium dicta et cupiditate inventore.', '1982-11-20 20:11:38');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (67, 'Modi omnis dolore alias illo. Odio ea officia velit magnam.', '1992-01-19 11:55:21');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (68, 'Quaerat neque aliquam sit laboriosam sequi ab veritatis. Possimus commodi optio ut. Et et aspernatur reprehenderit nulla molestiae.', '1982-09-10 00:07:01');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (69, 'Qui velit perferendis tenetur ut. Perferendis velit cum similique eligendi voluptas dicta. Iure neque sint voluptatem commodi neque sed a dolores.', '1994-06-30 17:55:57');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (70, 'Consequatur reiciendis quisquam possimus qui. Cupiditate voluptas quidem neque nulla consequatur impedit culpa molestias. Aliquid nihil architecto vero est ut nobis.', '1971-08-30 08:07:06');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (71, 'Incidunt officia impedit rem perspiciatis. Facilis reiciendis id neque aut in aut odio. Libero a voluptatem quia blanditiis. Voluptas molestias veritatis architecto.', '1979-12-15 15:27:40');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (72, 'Illum cupiditate eligendi magni odio explicabo. Et dolor commodi recusandae aut et dolorum velit. Inventore dignissimos ullam ea officia aspernatur repellat. Repellat eveniet nisi quasi nulla atque.', '1997-07-17 18:53:00');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (73, 'Explicabo esse in in optio cumque necessitatibus. Vel unde ad quia dolorem fuga. Et sed sit eum accusamus id voluptas error. Quia necessitatibus accusantium illum.', '1982-09-26 12:06:23');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (74, 'Nihil qui rerum velit quia. Et similique dolorem minima qui. Aspernatur occaecati aspernatur est ullam accusantium autem.', '2004-11-26 08:39:59');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (75, 'In quia expedita dolorum nesciunt esse temporibus ut. Ut commodi voluptatem error quos aliquam. Consectetur placeat ex minus quo quam doloremque omnis. Fugiat eveniet quos non dolorem.', '1976-03-23 20:14:26');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (76, 'Et non consectetur voluptas. Sit in sed amet ut. Vero adipisci aut totam nisi distinctio et itaque amet.', '1987-11-11 15:54:30');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (77, 'Ab qui autem dolorem ullam qui. Ab voluptatem autem mollitia. Qui rerum consequuntur debitis.', '2017-02-11 22:53:16');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (78, 'Aperiam quae voluptas qui deleniti ut quae. A ut accusamus quasi fugiat. Sunt odit incidunt sit vitae dolor iusto quidem.', '1989-08-14 22:20:35');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (79, 'Molestiae vel est beatae voluptas tenetur asperiores. Voluptates dolor sed in dolorem. Non facere aut et possimus sit nobis ab. Blanditiis corporis dolore velit suscipit a quo ea quo.', '1972-02-02 18:36:55');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (80, 'Nisi ipsa cupiditate natus ea laboriosam pariatur ipsum magnam. Perferendis quia qui sed occaecati odio dolor.', '1983-11-17 04:57:12');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (81, 'Ipsum recusandae omnis quaerat fuga et. Laborum accusantium enim officia doloremque iste est repellat. Sed velit et et sit consequatur. Eligendi quis necessitatibus rerum nam unde.', '1989-12-07 16:08:50');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (82, 'Quos unde sit itaque sit ipsa. Soluta at eius facilis. Enim et voluptatibus aperiam. Similique accusantium voluptates et nam.', '1985-09-24 06:49:37');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (83, 'Quia asperiores quidem suscipit magni inventore. Expedita dolorem aut libero tempora qui et.', '1991-10-30 13:36:54');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (84, 'Quasi nihil sit tempora iste. Deserunt reprehenderit id officia architecto tenetur illo qui. Ducimus et dolores quibusdam in. Cupiditate minus nobis non labore non ut impedit earum.', '2004-01-27 20:35:00');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (85, 'Rerum a ipsum fugiat numquam illum. Eum repellendus laborum ipsum et fugiat eum. Est laudantium eaque rerum eos. Eum rerum ut illum vel amet.', '1998-02-28 15:23:12');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (86, 'Aliquid quia consectetur praesentium earum. Asperiores quas ut autem quas. Molestias molestiae molestiae quia nam autem. Debitis et ut deserunt autem occaecati eius.', '1990-01-31 19:55:49');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (87, 'Minima suscipit ex maxime et dicta fuga. Veritatis ipsa molestiae repellendus autem. Quas eligendi provident nisi et quae quam repudiandae. Aut et in voluptatem.', '1977-06-01 05:16:02');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (88, 'Qui in atque sapiente sit incidunt sed. Magni voluptatum omnis dolores totam nesciunt dicta. Dolor quisquam magnam explicabo sunt.', '2012-08-22 06:51:40');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (89, 'Sit ut nihil nemo voluptatem ad necessitatibus. Sed provident aspernatur et a asperiores quasi architecto. Culpa optio et corporis consequatur eos possimus.', '1985-01-29 02:32:58');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (90, 'Eligendi facilis alias eaque iste magnam. Qui ad qui dolor est corrupti delectus fugit. Cupiditate harum et cumque quod.', '2005-01-19 07:03:15');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (91, 'Nihil saepe illum aut doloremque. Quia voluptatibus repudiandae quasi dolore architecto rerum est eum. Quibusdam consectetur aliquid saepe dolores nihil velit ut. Animi quia in quia vel eos.', '1985-06-15 21:27:37');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (92, 'Consectetur earum eum voluptatibus magnam excepturi. Soluta voluptas alias reiciendis quia animi incidunt. Laboriosam iure dicta et eaque repellendus laboriosam eos tenetur.', '1985-03-08 07:36:09');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (93, 'Quo placeat laudantium sint provident eos eveniet. Magni assumenda voluptatem tenetur ullam reprehenderit animi ratione. Quisquam consequuntur et sit occaecati laboriosam et.', '2019-07-19 09:32:38');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (94, 'Vero quasi enim quibusdam quas praesentium repellat. Dolore reprehenderit non quae nobis asperiores consequatur. Est ducimus architecto exercitationem quam reprehenderit eius.', '1994-03-16 06:37:03');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (95, 'Dolores aperiam quidem temporibus nam ut quaerat eos. Qui dolorem dicta quia aut porro qui ut. Provident et voluptatibus error rerum. Aut praesentium qui amet voluptatem.', '2008-05-09 07:59:41');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (96, 'Labore laboriosam eum neque dolorem. Qui molestias fugit corporis ad rerum veritatis. Vero voluptatem soluta est aut qui expedita debitis. Quidem cumque non et rerum quas.', '1985-02-16 17:53:45');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (97, 'Vitae dignissimos placeat doloribus dolores praesentium exercitationem commodi culpa. Perferendis id ducimus dolorum in eligendi est. Est nesciunt quia reiciendis reiciendis quaerat nulla.', '1992-12-26 04:30:35');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (98, 'Excepturi eaque eos quam illo. Doloremque eaque veniam nisi blanditiis adipisci eaque ducimus. Neque animi eos aut adipisci voluptatem error atque. Ipsam temporibus quos fuga.', '1996-09-01 05:28:13');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (99, 'Porro amet minima totam est. Error aut quae et eius voluptas odit molestiae nulla. Accusamus harum ut vero officia fugit hic architecto blanditiis. Et quam dolorum culpa quos eum.', '1997-10-22 07:25:04');
INSERT INTO `Sequestro` (`ID`, `Descrizione`, `Data_ritiro`) VALUES (100, 'Neque laboriosam non aut fugiat. Cumque non culpa debitis et suscipit vel. Ratione iusto asperiores dolores esse nisi reiciendis. Labore ut officia rem.', '1981-06-09 04:33:57');
