USE 5ai_19_20_s01118;

CREATE TABLE IF NOT EXISTS 191203_attore (
	codAttore INT(11) NOT NULL AUTO_INCREMENT,
	nome VARCHAR(30) DEFAULT NULL,
	cognome VARCHAR(30) NOT NULL,
	annoNascita YEAR DEFAULT NULL,
	nazionalita VARCHAR(30) DEFAULT NULL,
	PRIMARY KEY(codAttore)
);

CREATE TABLE IF NOT EXISTS 191203_film (
	codFilm INT(11) NOT NULL AUTO_INCREMENT,
	titolo VARCHAR(50) NOT NULL,
	-- TODO
);
